package com.multi.dto;

public enum DBParameter {  // Body-параметры (их названия) json телеграммы
    iStation,
    iDest,
    iGetTrack,
    iPutTrack,
    iShuttleTrack,
    iTrack1,
    iTrack2,
    iTrack3,
    iTrack4,
    iTrack5,
    iTrack6,
    iTrack12,
    iTrack23,
    iTrack34,
    iPosition1,
    iPosition2,
    iSegment1,
    nM2,
    nLength,
    nWidth,
    iSubStackL,
    iSubStackW,
    nStackWeight,
    iSheetCnt,
    iCaliper,
    iDeleteSubstack,
    nFillgrade,
    iRejected,
    sFlute,
    sOrderNumber,
    sLastMoveFormat,
    sText,
    iPLC,
    iDW,
    iValue,
    nOldValue,
    nNewValue,
    iFunctionS,
    iFunctionD,
    iFunctionSR,
    iFunctionDR,
    iFunctionTT,
    iTimeCreated,
    iClass,
    iOperatorDesk,
    iAction,
    iActionIndex;

    private DBParameter() {
    }
}
